[package]
name = "cldi"
version = "0.3.0"
authors = ["Zhishi <whfuyn@outlook.com>"]
edition = "2021"

[features]
default = ["evm", "crypto_sm"]
# default = ["evm", "crypto_eth"]

evm = []
chaincode = [] # unimplemented yet

crypto_sm = ["libsm", "efficient-sm2"]


[dependencies]
clap = "3.1"
clap_complete = "3.1"
hex = "0.4"
tokio = { version = "1.6", features = ["full"] }
rand = "0.8"
tonic = "0.6"
prost = "0.9"
time = { version = "0.3.5", features = ["formatting", "local-offset"] }
serde = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
thiserror = "1.0"
anyhow = "1.0"
home = "0.5.3"
rustbreak = { version = "2.0", features = ["ron_enc"] }
indicatif = "0.16.2"
rayon = "1.5.1"
tentacle-multiaddr = "0.3.1"
toml = "0.5"
rustyline = "9.1"
shell-words = "1.0"
parking_lot = "0.12"
mockall = { version = "0.11", features = ["nightly"] }
tempfile = "3.3"

# crypto_sm
libsm = { version = "0.4.0", optional = true }
efficient-sm2 = { version = "0.1.5", optional = true }

# crypto_eth
aes = "0.7"
ctr = "0.8"
tiny-keccak = { version = "2.0", features = ["keccak"] }
secp256k1 = { version = "0.21", features = ["rand-std", "recovery"] }

[build-dependencies]
tonic-build = "0.6"

[dev-dependencies]
tempfile = "3.3"

[profile.release]
lto = true
