[package]
name = "cldi"
version = "0.1.0"
authors = ["Zhishi <whfuyn@outlook.com>"]
edition = "2018"

[features]
default = ["evm", "crypto_sm"]
# default = ["evm", "crypto_eth"]

evm = []
chaincode = [] # unimplemented yet

crypto_sm = ["libsm", "efficient-sm2"]
crypto_eth = ["aes", "ctr", "tiny-keccak", "secp256k1"]


[dependencies]
rustyline = "8.2"
clap = "=3.0.0-beta.2"
clap_generate = "=3.0.0-beta.2"
hex = "0.4"
tokio = { version = "1.6", features = ["full"] }
futures = "0.3"
rand = "0.8"
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto" }
tonic = "0.5"
prost = "0.8"
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
lazy_static = "1.4.0"
anyhow = "1.0"
home = "0.5.3"
rustbreak = { version = "2.0", features = ["ron_enc"] }

# crypto_sm
libsm = { version = "0.4.0", optional = true }
efficient-sm2 = { git = "https://github.com/Pencil-Yao/efficient-sm2", optional = true }

# crypto_eth
aes = { version = "0.7", optional = true }
ctr = { version = "0.7", optional = true }
tiny-keccak = { version = "2.0", features = ["keccak"], optional = true }
secp256k1 = { version = "0.20", features = ["rand-std", "recovery"], optional = true }
