[package]
name = "cldi"
version = "0.1.0"
authors = ["Zhishi <whfuyn@outlook.com>"]
edition = "2018"

[features]
default = ["evm"]
evm = ["cloud-client/evm"]
chaincode = ["cloud-client/chaincode"]

[dependencies]
rustyline = "8.2.0"
clap = "3.0.0-beta.2"
cloud-client = { path = "cloud-client" }
hex = "0.4"
tokio = { version = "1.3", features = ["full"] }
futures = "0.3.15"
rand = "0.8.3"
